server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.199.231:80

management:
  endpoints:
    web:
      exposure:
        include: "*"