server:
  port: 7003
eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka/
