server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment

eureka:
  instance:
    instance-id: payment8001
    prefer-ip-address: true #访问路径可显示IP地址
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka