server:
  port: 80

spring:
  application:
    name: cloud-consumer-feign-hystrix-order

eureka:
  instance:
    instance-id: order80
    prefer-ip-address: true #访问路径可显示IP地址
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka/

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    org.xuquan.service.PaymentFeignService: debug

feign:
  hystrix:
    enabled: true